### ISSUE TITLE
unequal length warning

### ISSUE THREAD

**Issue by guitarvydas** [emotiq/emotiq#440]
"2018-08-15 09:51:32 WARN Unequal-length public-keys/tx-input hashes (#<PBC-INTERFACE:PUBLIC-KEY E32E046..3B6A201>) length = 1 vs. (#<COSI/PROOFS/NEWTX::TRANSACTION-INPUT 4020014823> #<COSI/PROOFS/NEWTX::TRANSACTION-INPUT 402001486B> #<COSI/PROOFS/NEWTX::TRANSACTION-INPUT 40200148B3>) length = 3. Programming error likely!"

Intermittent.

reproduce, intermittently, with multi-nodes in a single process, running emotiq/app::test-app

**Comment by dbmcclain** [comment]
Never heard of this error. Sounds like possibly a misunderstanding of the nature of hashes and public keys, as well as suffering some intermediate conversion to integer form and back again. Remember that leading zeros won't be preserved on conversion to INT form. So in general, don't do that except to make comparisons, but never to transfer information.

**Comment by dbmcclain** [comment]
Sounds like a leftover issue from before we started using tagged data. Need to be sure that functions and methods don't take inputs unless they match the expected tags. For instance, a function expecting a public key might be defined as a `(defun doit (pkey) ...)` instead of `(defmethod doit ((pkey public-key)) ...)`. Watch out for being too lax in the API.
